// Professional interests focused on career and industry skills
export const professionalInterests = [
  "Artificial Intelligence",
  "Blockchain",
  "Brand Management",
  "Business Development",
  "Business Strategy",
  "Cloud Computing",
  "Consulting",
  "Content Creation",
  "Crypto",
  "Cybersecurity",
  "Data Analytics",
  "Data Science",
  "DevOps",
  "Digital Marketing",
  "Entrepreneurship",
  "Financial Analysis",
  "HR Management",
  "Leadership",
  "Machine Learning",
  "Marketing",
  "Mobile Development",
  "Product Management",
  "Project Management",
  "Public Speaking",
  "Research",
  "Sales",
  "Software Development",
  "Teaching",
  "UI Design",
  "UX Design",
  "Web Development"
];

// Hobbies and personal interests
export const hobbyInterests = [
  "Art",
  "Baseball",
  "Basketball",
  "Blogging",
  "Board Games",
  "Chess",
  "Cooking",
  "Crafts",
  "Cycling",
  "Dancing",
  "Drawing",
  "Film",
  "Fitness",
  "Food Tasting",
  "Gaming",
  "Gardening",
  "Golf",
  "Guitar",
  "Hiking",
  "Hockey",
  "Lacrosse",
  "Language Learning",
  "MMA",
  "Meditation",
  "Music",
  "Painting",
  "Photography",
  "Piano",
  "Podcasting",
  "Reading",
  "Rock Climbing",
  "Running",
  "Singing",
  "Skateboarding",
  "Skiing",
  "Snowboarding",
  "Soccer",
  "Surfing",
  "Swimming",
  "Tennis",
  "Theater",
  "Travel",
  "Volunteering",
  "Wrestling",
  "Writing",
  "Yoga"
];

// List of common languages
export const languages = [
  "English",
  "Spanish",
  "Mandarin Chinese",
  "Hindi",
  "Arabic",
  "French",
  "Portuguese",
  "Bengali",
  "Russian",
  "Japanese",
  "German",
  "Korean",
  "Italian",
  "Turkish",
  "Vietnamese",
  "Polish",
  "Dutch",
  "Thai",
  "Persian",
  "Greek",
  "Swedish",
  "Czech",
  "Romanian",
  "Hungarian",
  "Finnish",
  "Danish",
  "Slovak",
  "Norwegian",
  "Hebrew",
  "Ukrainian"
];

// Common companies that professionals might be interested in
export const desiredCompanies = [
  "Google",
  "Apple",
  "Microsoft",
  "Amazon",
  "Meta",
  "Tesla",
  "Netflix",
  "Adobe",
  "Salesforce",
  "Oracle",
  "Intel",
  "IBM",
  "Twitter",
  "LinkedIn",
  "Airbnb",
  "Uber",
  "SpaceX",
  "Goldman Sachs",
  "JPMorgan Chase",
  "Morgan Stanley",
  "Deloitte",
  "McKinsey",
  "Boston Consulting Group",
  "NVIDIA",
  "Samsung",
  "Sony",
  "Disney",
  "Nike",
  "Spotify",
  "Slack"
];