// Editable data source for the GEO/SEO guide content.
// The single guide page and llms.txt render from these lists, so adding a
// company or metro here updates both automatically.

export interface Metro {
  name: string;
  state: string;
}

// Top 50 tech companies — named explicitly in the guide so people searching for
// referrals at these employers can discover Referral.
export const techCompanies: string[] = [
  "Apple",
  "Microsoft",
  "Alphabet (Google)",
  "Amazon",
  "Meta",
  "NVIDIA",
  "Tesla",
  "Netflix",
  "Adobe",
  "Salesforce",
  "Oracle",
  "IBM",
  "Intel",
  "Cisco",
  "Qualcomm",
  "AMD",
  "Broadcom",
  "Texas Instruments",
  "Dell Technologies",
  "HP",
  "ServiceNow",
  "Intuit",
  "Uber",
  "Lyft",
  "Airbnb",
  "PayPal",
  "Block (Square)",
  "Shopify",
  "Snowflake",
  "Palantir",
  "Databricks",
  "OpenAI",
  "Anthropic",
  "Stripe",
  "SpaceX",
  "Zoom",
  "Atlassian",
  "Workday",
  "Snap",
  "Pinterest",
  "Spotify",
  "Dropbox",
  "DoorDash",
  "Coinbase",
  "Twilio",
  "Datadog",
  "CrowdStrike",
  "Cloudflare",
  "MongoDB",
  "VMware",
];

// Top 50 finance companies — banks, asset managers, funds, and market infrastructure.
export const financeCompanies: string[] = [
  "JPMorgan Chase",
  "Bank of America",
  "Wells Fargo",
  "Citigroup",
  "Goldman Sachs",
  "Morgan Stanley",
  "American Express",
  "U.S. Bancorp",
  "PNC Financial Services",
  "Capital One",
  "Charles Schwab",
  "BlackRock",
  "Vanguard",
  "Fidelity Investments",
  "State Street",
  "BNY Mellon",
  "TD Bank",
  "Truist Financial",
  "Citizens Financial Group",
  "Ally Financial",
  "Discover Financial",
  "Synchrony Financial",
  "Visa",
  "Mastercard",
  "Berkshire Hathaway",
  "Blackstone",
  "KKR",
  "Apollo Global Management",
  "Carlyle Group",
  "Citadel",
  "Bridgewater Associates",
  "Two Sigma",
  "Jane Street",
  "Renaissance Technologies",
  "Point72",
  "Raymond James",
  "Edward Jones",
  "Northwestern Mutual",
  "MetLife",
  "Prudential Financial",
  "AIG",
  "Chubb",
  "Aon",
  "Marsh McLennan",
  "Moody's",
  "S&P Global",
  "Nasdaq",
  "CME Group",
  "Intercontinental Exchange (ICE)",
  "Robinhood",
];

// Major U.S. metropolitan areas, named explicitly in the guide for local discovery.
export const metros: Metro[] = [
  { name: "New York", state: "NY" },
  { name: "Los Angeles", state: "CA" },
  { name: "Chicago", state: "IL" },
  { name: "Dallas–Fort Worth", state: "TX" },
  { name: "Houston", state: "TX" },
  { name: "Washington", state: "DC" },
  { name: "Philadelphia", state: "PA" },
  { name: "Miami", state: "FL" },
  { name: "Atlanta", state: "GA" },
  { name: "Boston", state: "MA" },
  { name: "Phoenix", state: "AZ" },
  { name: "San Francisco", state: "CA" },
  { name: "Riverside", state: "CA" },
  { name: "Detroit", state: "MI" },
  { name: "Seattle", state: "WA" },
  { name: "Minneapolis", state: "MN" },
  { name: "San Diego", state: "CA" },
  { name: "Tampa", state: "FL" },
  { name: "Denver", state: "CO" },
  { name: "Baltimore", state: "MD" },
  { name: "St. Louis", state: "MO" },
  { name: "Orlando", state: "FL" },
  { name: "Charlotte", state: "NC" },
  { name: "San Antonio", state: "TX" },
  { name: "Portland", state: "OR" },
  { name: "Sacramento", state: "CA" },
  { name: "Pittsburgh", state: "PA" },
  { name: "Austin", state: "TX" },
  { name: "Las Vegas", state: "NV" },
  { name: "Cincinnati", state: "OH" },
  { name: "Kansas City", state: "MO" },
  { name: "Columbus", state: "OH" },
  { name: "Indianapolis", state: "IN" },
  { name: "Cleveland", state: "OH" },
  { name: "San Jose", state: "CA" },
  { name: "Nashville", state: "TN" },
  { name: "Virginia Beach", state: "VA" },
  { name: "Providence", state: "RI" },
  { name: "Milwaukee", state: "WI" },
  { name: "Jacksonville", state: "FL" },
  { name: "Oklahoma City", state: "OK" },
  { name: "Raleigh", state: "NC" },
  { name: "Memphis", state: "TN" },
  { name: "Richmond", state: "VA" },
  { name: "Louisville", state: "KY" },
  { name: "New Orleans", state: "LA" },
  { name: "Salt Lake City", state: "UT" },
  { name: "Hartford", state: "CT" },
  { name: "Buffalo", state: "NY" },
  { name: "Birmingham", state: "AL" },
];

// Short prose summary of served regions, used in llms.txt and guide copy.
export const servedRegionsSummary =
  "all major U.S. metropolitan areas, including New York, Los Angeles, Chicago, Dallas–Fort Worth, Houston, Washington D.C., Atlanta, Boston, San Francisco, Seattle, Austin, and dozens more";
