{pkgs}: {
  deps = [
    pkgs.libxkbcommon
    pkgs.xorg.libXScrnSaver
    pkgs.xorg.libXcursor
    pkgs.xorg.libXtst
    pkgs.xorg.libXi
    pkgs.xorg.libxcb
    pkgs.xorg.libXrandr
    pkgs.xorg.libXfixes
    pkgs.xorg.libXext
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.xorg.libX11
    pkgs.expat
    pkgs.mesa
    pkgs.libdrm
    pkgs.at-spi2-core
    pkgs.at-spi2-atk
    pkgs.alsa-lib
    pkgs.cairo
    pkgs.pango
    pkgs.gtk3
    pkgs.cups
    pkgs.atk
    pkgs.dbus
    pkgs.nspr
    pkgs.nss
    pkgs.glib
    pkgs.chromium
    pkgs.util-linux
    pkgs.wget
    pkgs.zip
    pkgs.imagemagick
    pkgs.jq
    pkgs.lsof
    pkgs.poppler_utils
    pkgs.postgresql
  ];
}
